### ISSUE TITLE
TextView text disappears when chooser view appears

### ISSUE THREAD

**Issue by erikackermann** [linkedin/Hakawai#10]
With the 3.1.0 release, custom fonts for selected/unselected mentions are working (not sure if this is related).

But, as soon as the mention chooser view appears, all text in the TextView disappears.  I can continue typing (although I can't see what I'm entering); as soon as the chooser view disappears, all of the text comes back, still with the correct formatting.

**Comment by austinzheng** [comment]
Would you be willing to attach a screenshot? If you don't want to make it public you can email me; my username is the same as it is here and I use Google's email service.

Also, could you attach the attributes you're using?

**Comment by austinzheng** [comment]
Also, which chooser mode are you using? I assume `HKWMentionsChooserPositionModeCustomLockBottomNoArrow`?

Any mode with 'Lock Bottom' forces the entry point to the bottom of the text view (and any mode with 'Lock Top' forces the entry point to the top of the text view). That might not be what you wanted; can you try it with `HKWMentionsChooserPositionModeCustomNoLockNoArrow`?

Thanks so much, and sorry this is proving such a hassle.

**Comment by erikackermann** [comment]
I'll try `HKWMentionsChooserPositionModeCustomNoLockNoArrow` and see if that helps, and I can send  a screenshot shortly.

Thanks for your help!  I really appreciate it.

**Comment by erikackermann** [comment]
Alright, `HKWMentionsChooserPositionModeCustomNoLockNoArrow` appears to fix the issue.  I imagine the other chooser modes were causing the text in the TextView to be scrolled out of view and that's why I saw it disappear.  I think we can close this one.

**Comment by austinzheng** [comment]
I may break up that enum from hell to make it less confusing. At the very least the documentation will be updated and screenshots added.
