### ISSUE TITLE
Feature request: add method to Mentions delegate to notify when a mention is created

### ISSUE THREAD

**Issue by erikackermann** [linkedin/Hakawai#11]
It would be nice to have some easy interface to know when an @mention is added.

(Additionally, it would be nice if the standard UITextView delegate was called with `-textViewDidChange:` when these @mentions are added).

**Comment by austinzheng** [comment]
Sorry, I was indisposed these last few days. I'll get to this soon.

**Comment by erikackermann** [comment]
Thanks.

**Comment by austinzheng** [comment]
Would this delegate method signature be sufficient for your purposes?

`- (void)mentionsPluginCreatedMention:(id<HKWMentionsEntityProtocol>)entity atLocation:(NSUInteger)location`

**Comment by erikackermann** [comment]
Yeah, that looks great.

On Mon, Mar 2, 2015 at 6:41 PM, Austin Zheng <notifications@github.com>
wrote:

> Would this delegate method signature be sufficient for your purposes?
>
> - (void)mentionsPluginCreatedMention:(id<HKWMentionsEntityProtocol>)entity
> atLocation:(NSUInteger)location
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkedin/Hakawai/issues/11#issuecomment-76852068>.
>



-- 
*Erik Ackermann*
Mobile Development | Hightower, Inc
212-951-0496 | erik@gethightower.com | LinkedIn
<http://www.linkedin.com/pub/erik-ackermann/94/66b/892/>

**Comment by austinzheng** [comment]
Added support for this in 3.2.0. Please check out the (new) changelog in the wiki for more details on the new features. (Also note that the method signature is a bit different than the one above.)
