### ISSUE TITLE
UIControl bounds

### ISSUE THREAD

**Issue by nferruzzi** [linkedin/Hakawai#13]
Hello, I noticed the bounds of the child UIControl do not resize properly (also confirmed on the demo app using "Debug view hierarchy" with iPhone5S emulator). For me this is a problem, because I move my textview around using constraints to set it to fullscreen and uicontrol do not get the proper bounds this way; from an end user point of view some portions of the "single line" textview are not sensible to touch gestures when the mention plugin is visible.

At the moment I've been able to do a workaround for ios8 (not working on ios7) using constraints and removing the explicit code to sync its frame with the textview one (ie setFrame and layoutSubview) but there is probably an easier fix. Any help is appreciated, thanks :)

**Comment by austinzheng** [comment]
I'll take a look at this ASAP.

**Comment by austinzheng** [comment]
Good catch. The view in question is having its frame manually set. I must have missed this when I converted the text view to use Auto Layout a long time ago; I'm surprised it didn't break sooner. I'll fix this as soon as I can.

**Comment by austinzheng** [comment]
Should be fixed in 3.2.1. Please re-open if you see any more problems.
