### ISSUE TITLE
Mentions plugin "disappears"

### ISSUE THREAD

**Issue by nferruzzi** [linkedin/Hakawai#14]
Hello,
my view hierarchy is like this

* controller view
* * tableview 
* * * tableviewcell (contentView)
* * * * container view
* * * * * hakawai text view, configured with mention plugin, with a small frame (ie 200x64)

when the textview becomes first responder on "keyboard will appear" I change the hierarchy like this (by calling [self.view addSubview:containerView] and then applying fullscreen constraints)

* controller view
* tableview
* * tableviewcell (contentView)
* container view (with proper fullscreen frame)
* * hakawai text view 
* * chooser view

unfortunately at this point after I type some text I experience very strange problems when I trigger the mention plugin:

1) for an instant before the plugin table view appears I can see the background (like if there were no textview at all)

2) as soon as I try to "select" a mention the plugins disappear, the textview becomes empty, and no mention is appended, the cursor blink but when I try to trigger the plugin again it does not work

3) if I press backspace several times, it gets like reseted and then the control characted triggers the plugin again; sometimes at this point I can properly add a mention but as soon as I try to type more the textview becomes empy again

I understand this is bizarre, I'm using latest version from cocoapods. Any advice ?

**Comment by nferruzzi** [comment]
Please note, If I do not move the view around everything works fine.

**Comment by austinzheng** [comment]
Thanks for reporting this. I have just a few questions:

- Are you creating the text view from a XIB or using code (e.g. `alloc init`)?
- Can you paste in the version that CocoaPods is pulling in?

I ask because there was a similar issue, but it should have been fixed.

**Comment by nferruzzi** [comment]
Hello, thanks for your help.

I create the hierarchy from a XIB with some constraints set to match its superview edges; cocoapods is pulling this version
  - Hakawai (3.1.0):
    - Hakawai/Core (= 3.1.0)
    - Hakawai/Mentions (= 3.1.0)
  - Hakawai/Core (3.1.0)
  - Hakawai/Mentions (3.1.0):
    - Hakawai/Core

SPEC CHECKSUM
Hakawai: ad61ec60b71490fff3bfb27dcf92a15329579d24

**Comment by austinzheng** [comment]
Would you be willing to send me a demo project that exhibits this behavior? (If not that's fine.)

**Comment by nferruzzi** [comment]
sure I've been adapting the demo project on my fork to add a controller with the same configuration. At the moment with latest version it does not show any problem :+1: its not 100% like my app but very close, so Im confident. Ill let you know if 3.1.2 fixed it :) thanks for your time
https://github.com/nferruzzi/Hakawai

**Comment by nferruzzi** [comment]
I didn't experience any strange problem so far, I think you can close it :) tnx

**Comment by austinzheng** [comment]
Excellent. Please re-open if this same issue turns up again.
