### ISSUE TITLE
Include Emoticon will likely lead to a crash when deleting the mention text.

### ISSUE THREAD

**Issue by hainhathoang88** [linkedin/Hakawai#140]
Hakawai Cocoapods version 7.1.2

- Precondition: Make the text with a mention and emoticon. For example: @John 🧒🏻.
- Steps:
+ Keep the keyboard open.
+ Tap the remove button key until all the text get deleted
- Expected: All the text got deleted successfully
- Bug: App crashes after the letter "h" got delete

Error message: 
*** Assertion failure in -[HKWMentionsPlugin toggleMentionsFormattingAtRange:selected:], ../Hakawai/Hakawai/Mentions/HKWMentionsPlugin.m:561

**Comment by hainhathoang88** [comment]
Device: iPhone X iOS 12.0.1

**Comment by hainhathoang88** [comment]
Device: iPhone X iOS 12.0.1

**Comment by hainhathoang88** [comment]
Device: iPhone X iOS 12.0.1

**Comment by hainhathoang88** [comment]
Device: iPhone X iOS 12.0.1

**Comment by hainhathoang88** [comment]
Device: iPhone X iOS 12.0.1

**Comment by hainhathoang88** [comment]
Device: iPhone X iOS 12.0.1

**Comment by hainhathoang88** [comment]
Device: iPhone X iOS 12.0.1

**Comment by bkoatz** [comment]
we've added tests to fix this!
