### ISSUE TITLE
Cannot Initialize MentionsPluginV2 - Swift

### ISSUE THREAD

**Issue by gintechsystems** [linkedin/Hakawai#196]
When trying to setup the mentions plugin v2, it says it accepts no arguments when using in Swift 5.0.

Below is some example code that I have, but cannot pass in parameters it seems (I get errors).

Old code before updating to 7.3.6:
`mentionsPlugin = HKWMentionsPlugin(chooserMode: .enclosedBottom, controlCharacters: CharacterSet.init(charactersIn: "@"), searchLength: 2, unselectedColor: appDel.appActiveColor, selectedColor: UIColor.white, selectedBackgroundColor: appDel.appActiveColor)`

New code:
```
mentionsPlugin = HKWMentionsPluginV2()
mentionsPlugin.defaultChooserViewDelegate = self
mentionsPlugin.controlCharacterSet = CharacterSet.init(charactersIn: "@")
mentionsPlugin.implicitSearchLength = 2
```

**Comment by bkoatz** [comment]
let mentionsPlugin = HKWMentionsPluginV2.mentionsPlugin(

            withChooserMode: .enclosedBottom,

            controlCharacters: CharacterSet(charactersIn: "@"),

            searchLength: 2,

            unselectedColor: appDel.appActiveColor, 
selectedColor: UIColor.white, 

selectedBackgroundColor: appDel.appActiveColor)



should work



i think you're just missing the "withChooserMode"

**Comment by gintechsystems** [comment]
Ahhh, I was not using the .mentionsPlugin after V2 either. That is somewhat weird, as usually it just takes parameters within the class itself. I didn't even think to do .mentionsPlugin as that just seems like an unusual case? Thanks for the help though, that did help. This is what it looks like now:

```
mentionsPlugin = HKWMentionsPluginV2.mentionsPlugin(withChooserMode: .enclosedTop, controlCharacters: CharacterSet.init(charactersIn: "@"), searchLength: 2, unselectedColor: appDel.appActiveColor, selectedColor: UIColor.white, selectedBackgroundColor: appDel.appActiveColor)
mentionsPlugin.defaultChooserViewDelegate = self
```

I am having one other problem, the popup that shows the cells does not seem to fill the screen, would I need to create a custom view to fix that issue?

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-02 at 15 43 14](https://user-images.githubusercontent.com/10021307/92029140-1a628280-ed33-11ea-8632-52804683c5fc.png)

**Comment by gintechsystems** [comment]
Looks like when you type characters using V2 it never updates the filtered results, I went back to using V1 until fixed.
