### ISSUE TITLE
'HKWMentionsPlugin' cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by iosappsdevelopers** [linkedin/Hakawai#199]
I am getting below error: -
'HKWMentionsPlugin' cannot be constructed because it has no accessible initializers.

Please share me solutions if any.

**Comment by bkoatz** [comment]
you can use HKWMentionsPluginV1, until V2 is ready

Best

**Comment by iosappsdevelopers** [comment]
Thanks, @bkoatz .

Currently I can see list for selection, when I tap on textview but it should only appear when I type @. 

Can you tell how can I prevent to appear list when I click on textview first time.

**Comment by robmathers** [comment]
Is this documented anywhere? Must admit it seems a little strange to have non-working code shipping in a production version.

**Comment by bkoatz** [comment]
we are updating documentation asap :) and if u instantiate your plugin with searchLength of 0 and a control character set inlcuding @ it should work @iosappsdevelopers
