### ISSUE TITLE
HKWMentionsPluginV2 does not call asyncRetrieveEntities() after the initial control character call

### ISSUE THREAD

**Issue by KrisConrad** [linkedin/Hakawai#203]
When using the `HKWMentionsPluginV2`, I'm seeing `asyncRetrieveEntities() `being called once when the control character is detected but it is not called again after that when subsequent characters are typed into the text field.

```
        mentionsPlugIn = HKWMentionsPluginV2.mentionsPlugin(
            withChooserMode: chooserMode,
            controlCharacters:  CharacterSet(charactersIn: "@"),
            searchLength: 0,
            unselectedColor: .chatBubbleBlue,
            selectedColor: .invertedTextMain,
            selectedBackgroundColor: .invertedBackgroundMain
        )

        mentionsPlugIn.stateChangeDelegate = self
        mentionsPlugIn.defaultChooserViewDelegate = self

        textView.controlFlowPlugin = mentionsPlugIn
```

If I change `mentionsPlugIn = HKWMentionsPluginV2.mentionsPlugin(` to `mentionsPlugIn = HKWMentionsPluginV1.mentionsPlugin(` `asyncRetreiveEntities()` is called after every character again as expected. The only problem is that `HKWMentionsPluginV1` doesn't react properly when I programmatically add the control character to the text view.

**Comment by prabhatVinsol** [comment]
@KrisConrad 
Have you got any workaround for this or any fix?

**Comment by KrisConrad** [comment]
> @KrisConrad 
> 
> Have you got any workaround for this or any fix?

No, unfortunately I had to fallback to using HKWMentionsPluginV1. it works but I've had to remove the @ button from the toolbar in my app because I can't add the mention character programmatically with HKWMentionsPluginV1. 

No work from the Hakawai team either at this point.

**Comment by bkoatz** [comment]
i'm sorry about the delay. in order for hkwmentionspluginv2 to work, make sure to set HKWTextView.enableMentionsPluginV2 = YES. we'll be updating documentation asap
