### ISSUE TITLE
Khmer (Cambodian) Language tagging issue 

### ISSUE THREAD

**Issue by purva-dev** [linkedin/Hakawai#232]
I'm facing issue in adding the mention attribute of **khmer language** text.
i.e not able to create a tag for khmer language always **returns nil** 

![Screenshot 2021-03-24 at 5 31 00 PM](https://user-images.githubusercontent.com/49225767/112462054-a2b77c00-8d86-11eb-9f6b-7934dec05479.png)

![Screenshot 2021-03-24 at 5 31 33 PM](https://user-images.githubusercontent.com/49225767/112462046-9f23f500-8d86-11eb-9224-ddee61a4edf3.png)

**Comment by bkoatz** [comment]
we have not tested with khmer before as it's not supported on LI. we can try and look through what the issue is, but encourage you to look around as well!

**Comment by purva-dev** [comment]
@bkoatz 
Hello there!! Thanks for your reply and now We would like to add here that we figured out the issue is where the string which we are sending in length to create **NSRange** is type of **String**

` let myNSRange = NSRange(location: aStartIndex, length: aStrName.count)`

so we just have to convert the **String** type to **NSString** like this

` let myNSRange = NSRange(location: aStartIndex, length: (aStrName as NSString).length)`

by this we can get the proper length of the string for creating **_HKWMentionsAttribute_**


### > **Another Way**


 we can also use **"unicodeScalars.count"** to calculate correct length of string

` let myNSRange = NSRange(location: aStartIndex, length: aStrName.unicodeScalars.count)`

**Comment by bkoatz** [comment]
Please feel free tp put up a PR, including tests :)
