### ISSUE TITLE
How to set the placeholder for HKWTextView?

### ISSUE THREAD

**Issue by ikousik** [linkedin/Hakawai#27]
How can I set the placeholder for HKWTextView ? I have UITextView instance of HKWTextView. I have set the delegate to implement the features.Now I am trying to call textViewDidBeginEditing and  textViewDidEndEditing,but none of these delegate getting called.

```
        _postTextView.simpleDelegate = self;
        _postTextView.externalDelegate = self;
```

But textViewDidBeginEditing and textViewDidEndEditing not getting called.
- (void)textViewDidBeginEditing:(HKWTextView *)textView
  {
  //want to call this
  }
- (void)textViewDidEndEditing:(HKWTextView *)textView
  {
   //want to call this
  }

How to do this?

**Comment by jsdu** [comment]
any updates on this?

**Comment by jsdu** [comment]
I am able to get textViewDidChange:(UITextView *)textView to work by implementing textView.simpleDelegate = self. 
Try changing HKWTextview to UITextview 
Still not sure how to implement Placeholders.

**Comment by jaja-digitalspaceexplorer** [comment]
@ikousik @jsdu I ported multiple libraries (Swift to Objective C) including [KMPlaceholderTextView](https://github.com/MoZhouqi/KMPlaceholderTextView) mechanism in the implementation of the HKWTextView. Just hooked them on the `-setup` method and you got a HKWTextView with a better placeholder.

**Comment by dgattey** [comment]
We don't offer direct support for placeholder text, but we'll think about it for the future. Thanks!
