### ISSUE TITLE
Error on 3DTouch Select

### ISSUE THREAD

**Issue by narlei** [linkedin/Hakawai#33]
Error when using 3DTouch keyboard text selection:

*Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString setCursorPosition:]: unrecognized selector sent to instance*

OR

[_NSActivityAssertion setCursorPosition:]: unrecognized selector sent to instance

**Comment by dgattey** [comment]
Hmm, not seeing this myself. Are you using the latest release? Still happening?

**Comment by narlei** [comment]
Hello @dgattey with the last version:
`[BKSProcessAssertion setCursorPosition:]`
- Start a text, insert a mention, write more text.
- With iOS Keyboard use 3D Touch to move cursor position over the mentions. The app crashes.

With GBoard Keyboard by Google, the bug not works.

**Comment by narlei** [comment]
Here a video reproducing the error with Project Example.

[error.mp4.zip](https://github.com/linkedin/Hakawai/files/1018625/error.mp4.zip)

**Comment by sergstav** [comment]
Bug still exists.

**Comment by dgattey** [comment]
Thanks all - we're looking to merge the PR as soon as we can confirm it doesn't break anything else
