### ISSUE TITLE
control character appended in textview text on click of uibutton not working

### ISSUE THREAD

**Issue by github-prathma** [linkedin/Hakawai#34]
whenever the control character @ is appended in textview text on click of uibutton , chooser view doesn't open

**Comment by daniel-mihai** [comment]
@github-prathma  view https://github.com/linkedin/Hakawai/issues/18 - I added a comment there explaining how I did it

**Comment by github-prathma** [comment]
Thanks for the help...

Regards,
Prathma

**Comment by PatrickAdams** [comment]
@daniel-mihai @github-prathma this doesn't seem to work for me. I can't get the plugin to activate when I manually append a control character to the textView.text - even with #18

**Comment by github-prathma** [comment]
ya it doesn't work .. try using textview delegate function like this

    if([self.textView.delegate textView:self.textView
shouldChangeTextInRange:NSMakeRange(self.textView.text.length, 0)
replacementText:@"@"]) {

        [self.textView insertText:@"@"];

    }
and this will replace the character in specified range and will
automatically textview will be reset to its quiescent state for enabling
tagging.

Thanks.

**Comment by dgattey** [comment]
We need a nice way to programmatically trigger the mentions plugin or a way that already exists to do that. I don't know of it if it exists, but we'll close this ticket and use #18 for tracking this addition.
