### ISSUE TITLE
Buffer Bug 'resumeMentionsPriorString / buffer'

### ISSUE THREAD

**Issue by jaja-digitalspaceexplorer** [linkedin/Hakawai#48]
Bug: invalid prefix / buffer was sent to the delegate (plugin's mentionDelegate)

Steps to replicate:

* Make sure the plugin's `resumeMentionsCreationEnabled` property is set to `YES`

1.  Insert a random sentence.
2. Initiate to create a mention somewhere between the sentence.
3. Resign the HKWTextView
4. Make the HKWTextView as first responder
5. Invalid prefix / buffer was sent to the delegate **BUG**

**Comment by dgattey** [comment]
Looks like a more specific version of your other report, #49. Closing as duplicate but we'll look at both, thanks.
