### ISSUE TITLE
Feature request: expose more generic interface for customizing Mentions plugin chooser view

### ISSUE THREAD

**Issue by erikackermann** [linkedin/Hakawai#5]
Currently the HKWMentionsPlugin can take a custom chooser view by subclassing `HKWAbstractChooserView` but this implementation has two major limitations:
 - The custom chooser view adopt the two table view protocols
 - The chooser view cannot be set to rest upon the keyboard (i.e. the text field's `inputAccessoryView`)

**Comment by austinzheng** [comment]
Hi Erik,

I've prepared a patch to address the first issue and will push it at some point this week (pending below). It includes a more generic way to define custom chooser views, as well as an example of a chooser view (in the sample app) that does not rely upon table views.

As for the second issue, can you describe your intended use case in a bit more detail? For example, how wide or tall would the chooser view be? You can use the custom position options in conjunction with `setChooserTopLevelView:attachmentBlock:` to give the chooser view arbitrary constraints. Would that be a possibility for your use case, with or without modifications to the API? (For example, the custom attachment block currently gets the accessory view passed in as its only argument. Maybe if I passed in the text view as well the block could easily get the input view height and use it to constrain the accessory view.)

Let me know if you have any questions! Thanks again for your feedback.

Best regards,
Austin

**Comment by erikackermann** [comment]
Hello @austinzheng.  Thank you for your attention to this.

Regarding the second feature request, my use case is trying to attach the custom chooser view as the HKWTextView's `inputAccessoryView`.  Here is what I'm trying:

```objc
        UIView *keyboardToolbar = [[UIView alloc] init];
        keyboardToolbar.translatesAutoresizingMaskIntoConstraints = NO;
        
        [_mentionsPlugin setChooserTopLevelView:keyboardToolbar attachmentBlock:^(UIView *view) {
            //setup constraints here
        }];
        
        _commentTextView.inputAccessoryView = keyboardToolbar;
```

But this doesn't place the chooser view in the keyboardToolbar... I'm guessing I need to do this setup at a different time?  When I step through with the debugger I see that the HKWTextView's `customTopLevelView` is nil at the time of the attachment block firing.

Am I using this API incorrectly?  Thanks for your help.

**Comment by erikackermann** [comment]
Alright, think I've gotten this to work.  I moved the above code block to execute *after* the `controlFlowPlugin` is set to my `_mentionPlugin`.  Is this a bug (that I need to initialize and set things up in this order)?

**Comment by austinzheng** [comment]
Hi Erik,

Glad it ended up working. Yes, unfortunately there are a couple of orderings that need to be followed. I'm going to do some work to either make it clear through documentations/log warnings that they need to be followed, or rework them so that ordering doesn't matter.

Once that's done I'll push those and the new chooser view changes as v3.0.0. (If you want to see how v3 will work you can take a look at the in-progress wiki docs, click the 'wiki' link in the sidebar.)

Let me know if you have any questions!

Austin

**Comment by erikackermann** [comment]
This is great :+1: I really appreciate you looking at this so quickly!

The interface for the "Type B" custom chooser is exactly what I was envisioning.  Thanks again and let me know if I can help with developing or documenting any of this.

**Comment by austinzheng** [comment]
Will do! For now I think everything is good.

I've pushed v3.0.0 and it should be published on CocoaPods soon. 3.0.0 includes the changes I mentioned above. It also explicitly adds a warning to the docstring for any mentions plug-in API that requires you attach the plug-in to a text view first (such as the `setChooserTopLevelView:attachmentBlock:` API you mentioned).

Let me know if you have any further questions. Thanks again for filing this issue!

**Comment by erikackermann** [comment]
@austinzheng This is working great.  I am still having trouble setting the custom chooser view frame with `-setChooserTopLevelView:attachmentBlock:`.  If I set a height for my top level view, and then attempt to constrain the chooser view to match this height, I get an "unable to simultaneously satisfy constraints" error.  It appears that the height of the top level view is always being constrained to be 100.

**Comment by austinzheng** [comment]
I'll take a look tonight. Thanks for bringing this to my attention.

**Comment by erikackermann** [comment]
Thanks!  Again, let me know if I can help in any way.

**Comment by austinzheng** [comment]
If it's not too much of a bother, could you open a new issue and post:

* The 'unable to satisfy' errors you see in your log?
* A very brief description of your top level view and how it's related to the text view in the view hierarchy?

Thanks so much.

**Comment by erikackermann** [comment]
Created this issue: https://github.com/linkedin/Hakawai/issues/8
