### ISSUE TITLE
Typing emoji does not fire textViewDidChange delegate method

### ISSUE THREAD

**Issue by om-ha** [linkedin/Hakawai#53]
It doesn't fire any of the related UITextViewDelegate unless a regular character or backspace is used.

However it is noticeable that shouldChangeTextInRange is called with internal delegate. But external delegate version is not called...

This issue has already been mentioned and closed on the same day without a solution.

https://github.com/linkedin/Hakawai/issues/45

**Comment by om-ha** [comment]
If at least someone could point the culprit function or lines of code for me to investigate further.

**Comment by om-ha** [comment]
Well there's `didChangeAttributedTextTo` in **HKWTextViewDelegate** which detects emojis. But only works on the second insertion. Closing this I suppose.

**Comment by alexisbronchart** [comment]
@om-ha This text length check could lead to the issue. 
https://github.com/linkedin/Hakawai/blob/88889d6d1c6d4cb4b22f6dce3cc0bc8d6138cd3d/Hakawai/Mentions/HKWMentionsPlugin.m#L1356

An inserted emoji with a length of 2 won't be matched as an insertion and subsequently the delegate method won't be called. I would try doing the length check using `NSStringEnumerationByComposedCharacterSequences` enumeration.

**Comment by jaystepin** [comment]
Any update in this issue?

**Comment by om-ha** [comment]
@alexisbronchart  really appreciate the hint, will look into this when I get back to working on this bug.
@jaystepin  I ended up with this..

```
// partial fix for bug when entering ONLY emojis, textViewDidChange is not call.
// caveat: this function is called after the 2nd emoji is added...
func textView(_ textView: HKWTextView, didChangeAttributedTextTo newText: NSAttributedString, originalText: NSAttributedString, originalRange: NSRange) {
	// next button state
	if newText.string.trimmed.isEmpty {
		footerNextEditButton.isEnabled = false
	} else {
		footerNextEditButton.isEnabled = true
	}
}
```

**Comment by dgattey** [comment]
Yea this is due to assuming UTF-8 and UTF-16 views of the strings are the same. They're not. Moving away from `length` will help. Looking into this soon.

**Comment by dgattey** [comment]
Ah looks like #89 should fix this 🎉 Still getting fully familiar with the current state of the codebase but I believe that merging that should close this.
