### ISSUE TITLE
HKWTextView automatic resizing?

### ISSUE THREAD

**Issue by goxyed** [linkedin/Hakawai#71]
When scrolling property for UITextView is disabled textView resizes as content grows. Is that possible with HKWTextView?

**Comment by om-ha** [comment]
Yes, you'll have to use an extension for this not a subclass. Since you've already HKWTextView is a subclass.

See this:
https://github.com/hsusmita/GrowingTextViewHandler

Resize your textView from HKWTextViewDelegate's didChange from within your ViewController.

**Comment by dgattey** [comment]
Thanks for answering @om-ha
