### ISSUE TITLE
Hide the Top Arrow from Plugin

### ISSUE THREAD

**Issue by harishprabhakaran** [linkedin/Hakawai#77]
I have integrated `Hakawai` and it's working perfectly. 

One issue is I need to remove the top Line with the Arrow on top of the textview.

**Note: I'm using the default chooser view with custom table view cell.**

**Comment by dgattey** [comment]
Hey there! We don't currently allow for customizing the default chooser view. If you'd like to remove the top line, I'd recommend subclassing the default chooser view and modifying it yourself.
